### ISSUE TITLE
Array detection fails in IE11 when called from iframe

### ISSUE THREAD

**Issue by hashchange** [Sahadar/pubsub.js#10]
In IE11, when communicating across window boundaries (calling `subscribe()` from an embedded iframe), the array detection does not work. Passing a namespace array to `subscribe()` results in an error:

    nsString.split is not a function 
        at Object.subscribe (... pubsub.js:134)
        at Object.subscribe (... pubsub.js:251)
        etc

That is easy to fix by replacing the current array detection

    typeof nsString === 'object' && nsString instanceof Array

with more a robust version from an established libary. The the approach taken by Underscore, for instance, works well:

    function isArray (obj) { 
        return Array.isArray ? Array.isArray(obj) : Object.prototype.toString.call(obj) === '[object Array]';
    }

A PR is coming your way :)

**Comment by Sahadar** [comment]
Hi, haven't tested it cross frames on my own. Will have to add test cases for this.
Thanks for this PR.

**Comment by hashchange** [comment]
Fast as usual :) Thanks!
