### ISSUE TITLE
event published twice

### ISSUE THREAD

**Issue by pdwinkel** [Sahadar/pubsub.js#7]
The following code will publish the event twice:

```
'use strict';

var pubsub = require('pubsub.js').newInstance({
   recurrent: true
});

var subscription = pubsub.subscribe('hello', function() {
   console.log('hello world!');
});

pubsub.publish('hello', []);
```

Output:
```
hello world!
hello world!
```

I would expect only one event.

**Comment by Sahadar** [comment]
Hello,
Many thanks for this report. I've immediately fixed this bug and either added new test cases for "recurrent" option, feel free to report other issues that you have found. Improvement issues are also welcome.
