### ISSUE TITLE
Tag missing for v1.5.1

### ISSUE THREAD

**Issue by hashchange** [Sahadar/pubsub.js#9]
Version 1.5.1 doesn't get fetched with Bower because the release isn't tagged. 

Can you please add the tag? Thanks!

(I was just about to report a broken `context` option in `subscribeOnce` and then realised that you've already fixed it but Bower had fetched the previous version.)

**Comment by Sahadar** [comment]
Hi!
Thanks for your report, obviously I should have added it earlier.
https://github.com/Sahadar/pubsub.js/tree/v1.5.1

New tag up and running now.

**Comment by hashchange** [comment]
Now _that_ was fast. Thanks!
